### ISSUE TITLE
Compatibility with Capacitor 4?

### ISSUE THREAD

**Issue by Aymkdn** [Fir3st/capacitor-intent#1]
Hey,

Thanks for this plugin. Do you know if it's compatible with Capacitor 4? If yes, could you update the package.json to change the `peerDepencies`, please?

Thank you

**Comment by Fir3st** [comment]
Hi,

I'm using it Capacitor 4 app and it works, so it is compatible. I'll look at updating the dependencies as soon as I have some time, or you can open a pull request and change it yourself (with me just merging the changes afterwards).

**Comment by Aymkdn** [comment]
Thanks for the quick answer. I submitted a pull request.
