### ISSUE TITLE
App intents

### ISSUE THREAD

**Issue by tylerclark** [Fir3st/capacitor-intent#4]
Does this have anything to do with iOS intents or android only?

**Comment by Fir3st** [comment]
Android only

**Comment by tylerclark** [comment]
How confusing. Why isn't this called `capacitor-android-intent` since there is iOS intents that aren't apart of this plugin?

**Comment by Fir3st** [comment]
Because it was created to solve issues of package https://github.com/darryncampbell/darryncampbell-cordova-plugin-intent which is also android only and at the time, I didn't really address the naming 🤷
